CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- This DDL is generated by the database client, it is not complete.

-- USE ebizno;

--CREATE type T_USER as enum("merchant","client");

CREATE TABLE users(
    user_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    first_name text,
    last_name text,
    telephone text,
    bi VARCHAR(17),
    email text,
    password text,
    state boolean,
    user_type TEXT,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    PRIMARY KEY(user_id)
);


CREATE TABLE clients(
    client_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    PRIMARY KEY(client_id),
    CONSTRAINT fk_user_client
        FOREIGN key (user_id)
            REFERENCES users(user_id)
            ON DELETE CASCADE
);


CREATE TABLE merchants(
    merchant_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    PRIMARY KEY(merchant_id),
    CONSTRAINT fk_user_merchant
        FOREIGN key (user_id)
            REFERENCES users(user_id)
            ON DELETE CASCADE
);


CREATE TABLE products(
    product_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    merchant_id uuid NOT NULL,
    name text,
    localization text,
    price integer,
    area text,
    description text,
    state boolean,
    path text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    PRIMARY KEY(product_id),
    CONSTRAINT fk_merchant_product
        FOREIGN key (merchant_id)
            REFERENCES merchants(merchant_id)
            ON DELETE CASCADE
);

CREATE TABLE addresses(
    address_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    product_id uuid NOT NULL,
    province text,
    municipe text,
    district text,
    PRIMARY KEY(address_id),
    CONSTRAINT fk_product_address
        FOREIGN key (product_id)
            REFERENCES products(product_id)
            ON DELETE CASCADE
);

CREATE TABLE productfiles(
    productfile_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    product_id uuid NOT NULL,
    path text,
    PRIMARY KEY(productfile_id),
    CONSTRAINT fk_product_purchase
        FOREIGN key (product_id)
            REFERENCES products(product_id)
            ON DELETE CASCADE
);


CREATE TABLE wellets(
    wellet_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    user_id uuid,
    balance integer,
    debit_amount integer,
    credit_amount integer,
    debit integer,
    credit integer,
    tarife integer,
    iva integer,
    cancel boolean,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    PRIMARY KEY(wellet_id),
    CONSTRAINT fk_user_wellet
        FOREIGN key (user_id)
            REFERENCES users(user_id)
            ON DELETE SET NULL
);


CREATE TABLE purchases(
    purchase_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    client_id uuid,
    merchant_id uuid,
    product_id uuid,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    PRIMARY KEY(purchase_id),
    CONSTRAINT fk_client_purchase
        FOREIGN key (client_id)
            REFERENCES clients(client_id)
            ON DELETE CASCADE,
    
    CONSTRAINT fk_merchant_purchase
        FOREIGN key (merchant_id)
            REFERENCES merchants(merchant_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_product_purchase
        FOREIGN key (product_id)
            REFERENCES products(product_id)
            ON DELETE CASCADE
    
    
);